# Generated by Django 4.2.5 on 2023-11-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Department name')),
                ('deptCode', models.CharField(blank=True, max_length=24, unique=True, verbose_name='Department code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Department description')),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Filial name')),
                ('filialCode', models.CharField(blank=True, max_length=24, unique=True, verbose_name='Filial code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Filial description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Pls add SubDepartment name', max_length=255, unique=True, verbose_name='SubDept_name')),
                ('subDeptCode', models.CharField(blank=True, max_length=24, unique=True, verbose_name='SubDepartment code')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SubDepartments', to='organisation.department', verbose_name='Department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Departments', to='organisation.filial', verbose_name='Filial'),
        ),
    ]
