# Generated by Django 4.2.5 on 2023-11-11 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='deptCode',
            field=models.CharField(blank=True, max_length=24, unique=True, verbose_name='Код отдела'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание отдела'),
        ),
        migrations.AlterField(
            model_name='department',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Departments', to='organisation.filial', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Название отдела'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание филиала'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='filialCode',
            field=models.CharField(blank=True, max_length=24, unique=True, verbose_name='Код филиала'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название филиала'),
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SubDepartments', to='organisation.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='name',
            field=models.CharField(blank=True, help_text='Pls add SubDepartment name', max_length=255, unique=True, verbose_name='Название подотдела'),
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='subDeptCode',
            field=models.CharField(blank=True, max_length=24, unique=True, verbose_name='Код подотдела'),
        ),
    ]
