# Generated by Django 4.2.5 on 2023-11-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_alter_department_deptcode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='filial',
            options={'ordering': ['name'], 'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AlterModelOptions(
            name='subdepartment',
            options={'verbose_name': 'Подотдел', 'verbose_name_plural': 'Подотделы'},
        ),
    ]
