# Generated by Django 4.2.5 on 2023-11-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0003_alter_startip_options_alter_typesubject_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'ordering': ['start_ip'], 'verbose_name': 'IP - адрес', 'verbose_name_plural': 'IP - адреса'},
        ),
    ]
