# Generated by Django 4.2.5 on 2023-11-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkDate', '0002_importdare_alter_eventsforuser_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImportDare',
            new_name='ImportData',
        ),
    ]
