# Generated by Django 4.2.5 on 2023-11-17 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkDate', '0004_alter_eventsforuser_medicalexamination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsforuser',
            name='knowledgeTest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checkDate.knowledgetest', verbose_name='Проверка знаний'),
        ),
        migrations.AlterField(
            model_name='eventsforuser',
            name='medicalExamination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkDate.medicalexamination', verbose_name='Медосмотр'),
        ),
        migrations.AlterField(
            model_name='eventsforuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checkDate.userfordate', verbose_name='Пользователь'),
        ),
    ]
