# Generated by Django 4.2.5 on 2023-11-21 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkDate', '0005_alter_eventsforuser_knowledgetest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsforuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkDate.userfordate', verbose_name='Пользователь'),
        ),
    ]
