# Generated by Django 4.2.5 on 2023-11-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkDate', '0007_alter_eventsforuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsforuser',
            name='knowledgeTest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checkDate.knowledgetest', verbose_name='Следующая проверка знаний'),
        ),
        migrations.AlterField(
            model_name='eventsforuser',
            name='medicalExamination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkDate.medicalexamination', verbose_name='Следующий медосмотр'),
        ),
    ]
