# Generated by Django 4.2.5 on 2023-11-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_alter_department_deptcode'),
        ('checkDate', '0008_alter_eventsforuser_knowledgetest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfordate',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organisation.department', verbose_name='Отдел'),
        ),
    ]
