# Generated by Django 4.2.5 on 2023-11-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_alter_department_deptcode'),
        ('checkDate', '0008_alter_eventsforuser_knowledgetest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=256, null=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AlterModelOptions(
            name='userfordate',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='userfordate',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organisation.department', verbose_name='Отдел'),
        ),
    ]
