# Generated by Django 4.2.5 on 2023-11-27 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkDate', '0009_status_alter_userfordate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfordate',
            name='order_number',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Номер приказа'),
        ),
        migrations.AddField(
            model_name='userfordate',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checkDate.status', verbose_name='Статус'),
        ),
    ]
