# Generated by Django 4.2.5 on 2023-11-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testUser', '0004_alter_instruction_options_alter_position_options_and_more'),
        ('checkDate', '0011_alter_userfordate_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfordate',
            name='position',
        ),
        migrations.AddField(
            model_name='userfordate',
            name='position',
            field=models.ManyToManyField(blank=True, to='testUser.position', verbose_name='Должность'),
        ),
    ]
