# Generated by Django 4.2.5 on 2023-11-28 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_alter_department_deptcode'),
        ('checkDate', '0012_remove_userfordate_position_userfordate_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfordate',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organisation.department', verbose_name='Отдел'),
        ),
    ]
