# Generated by Django 4.2.5 on 2023-11-02 11:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instruction name')),
                ('all_view', models.BooleanField(default=False, verbose_name='All_vision')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Instructions', to='organisation.filial', verbose_name='Filial')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Position')),
            ],
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, verbose_name='Holiday name')),
                ('holiday_date', models.DateField(verbose_name='Holiday date')),
                ('descrIPAddresstion', models.TextField(blank=True, null=True, verbose_name='Holiday description')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated datetime')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created datetime')),
            ],
        ),
        migrations.CreateModel(
            name='StartIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$', 'Введите значение в формате int.int.int')], verbose_name='Start IP')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='TypeSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type subject')),
            ],
        ),
        migrations.CreateModel(
            name='StepForInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Step name')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('illustration', models.ImageField(blank=True, upload_to='', verbose_name='Illustration')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testUser.instruction', verbose_name='Instruction')),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='IPAddress')),
                ('inventory_number', models.IntegerField(blank=True, default=None, null=True, verbose_name='Inventory num')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisation.department', verbose_name='Department')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisation.filial', verbose_name='Filial')),
                ('start_ip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testUser.startip', verbose_name='Start IP')),
                ('type_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testUser.typesubject', verbose_name='Type subject')),
            ],
            options={
                'ordering': ['start_ip'],
            },
        ),
    ]
