# Generated by Django 4.2.5 on 2023-11-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testUser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPAddress',
        ),
        migrations.DeleteModel(
            name='StartIP',
        ),
        migrations.DeleteModel(
            name='TypeSubject',
        ),
    ]
