# Generated by Django 4.2.5 on 2023-11-11 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_alter_department_deptcode_and_more'),
        ('testUser', '0002_delete_ipaddress_delete_startip_delete_typesubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Instructions', to='organisation.filial', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название инструкции'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='descrIPAddresstion',
            field=models.TextField(blank=True, null=True, verbose_name='Описание праздника'),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='holiday_date',
            field=models.DateField(verbose_name='Дата праздника'),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Название праздника'),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='stepforinstruction',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='stepforinstruction',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stepforinstruction',
            name='illustration',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Иллюстрация'),
        ),
        migrations.AlterField(
            model_name='stepforinstruction',
            name='instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testUser.instruction', verbose_name='Инструкция'),
        ),
        migrations.AlterField(
            model_name='stepforinstruction',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название шага'),
        ),
    ]
