# Generated by Django 4.2.5 on 2023-11-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testUser', '0003_alter_instruction_filial_alter_instruction_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={'verbose_name': 'Инструкция', 'verbose_name_plural': 'Инструкции'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='publicholiday',
            options={'verbose_name': 'Праздник', 'verbose_name_plural': 'Праздники'},
        ),
        migrations.AlterModelOptions(
            name='stepforinstruction',
            options={'verbose_name': 'Шаг', 'verbose_name_plural': 'Шаги для инструкций'},
        ),
    ]
